spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinelist
    username: postgres
    password: postgres

  security:
    user:
      name: admin
      password: admin

  application:
    name: cinelist-api

  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

tmdb:
  api:
    key: a1d3782143dfab6136c44340f186dfc4

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
      expiration-time-in-seconds: 7200
