spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinelist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
      pool-name: CineList-db-pool
      max-lifetime: 6000000
      connection-timeout: 100000
      connection-test-query: select 1

  security:
    user:
      name: admin
      password: admin

  application:
    name: cinelist-api

  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

tmdb:
  api:
    key: a1d3782143dfab6136c44340f186dfc4


api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}


